config/routes.rb
Rails.application.routes.draw do
  resources :portfolio_items do
  	collection do
  		get :home
  	end
  end
  resources :posts

  devise_for :users

  root to: 'portfolio_items#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
  belongs_to :user

  before_validation :strip_id
  
  has_one_attached :preview_image

  validates :title, presence: true, length: { maximum: 120 }
  validates :description, presence: true, length: { maximum: 450 }
  validates :youtube_url, presence: true, format: { with: /\A(https?\:\/\/)?(www\.)?(youtube\.com|youtu\.?be)\/.+\z/,
  	message: "requires a complete YouTube URL"
	}

  def self.newest_first
    self.order(created_at: :desc)
  end

  def self.homepage_items
    newest_first.limit(3)
  end

	private

		def strip_id
      begin
  			self.youtube_id = YoutubeID.from(self.youtube_url)
      rescue
      end
		end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_rich_text :content
  has_one_attached :header_image

  default_scope { order(created_at: :desc) }

  validates :title, presence: true, length: { maximum: 120 }
  validates :summary, presence: true, length: { maximum: 450 }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :portfolio_items
	has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:new, :create]
  before_action :authenticate_user!, except: [:home, :index, :show]

  # GET /portfolio_items
  def index
    @portfolio_items = PortfolioItem.newest_first
  end

  # Serves as the root for the site. Displays 3 most recent portfolio items
  def home
    @portfolio_items = PortfolioItem.homepage_items
  end

  # GET /portfolio_items/1
  def show
  end

  # GET /portfolio_items/new
  def new
    @portfolio_item = @user.portfolio_items.build
  end

  # GET /portfolio_items/1/edit
  def edit
  end

  # POST /portfolio_items
  def create
    @portfolio_item = @user.portfolio_items.build(portfolio_item_params)

    if @portfolio_item.save
      flash[:success] = 'Portfolio item was successfully created.'
      redirect_to @portfolio_item 
    else
      flash.now[:danger] = "The form contains #{helpers.pluralize(@portfolio_item.errors.count, 'error')}"
      render :new
    end
  end

  # PATCH/PUT /portfolio_items/1
  def update
    if @portfolio_item.update(portfolio_item_params)
      flash[:success] = 'Portfolio item was successfully updated.'
      redirect_to @portfolio_item
    else
      flash.now[:danger] = "The form contains #{helpers.pluralize(@portfolio_item.errors.count, 'error')}"
      render :edit
    end
  end

  # DELETE /portfolio_items/1
  def destroy
    @portfolio_item.destroy
    flash[:notice] = 'Portfolio item was successfully destroyed.'
    redirect_to portfolio_items_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio_item
      @portfolio_item = PortfolioItem.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_item_params
      params.require(:portfolio_item).permit(:title, :description, :youtube_url, :preview_image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:new, :create]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = @user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = @user.posts.build(post_params)

    if @post.save
      flash[:succes] = 'Post was successfully created.' 
      redirect_to @post
    else
      flash.now[:danger] = "The form contains #{helpers.pluralize(@post.errors.count, 'error')}"
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      flash[:succes] = 'Post was successfully updated.' 
      redirect_to @post
    else
      flash.now[:danger] = "The form contains #{helpers.pluralize(@post.errors.count, 'error')}"
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    flash[:notice] = 'Post was successfully destroyed.'
    redirect_to posts_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :summary, :content, :header_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def inline_error(field, record)
		errors = record.errors

		if errors.include?(field)
			errors.full_messages_for(field).each do |error|
				concat content_tag(:p, error, class: 'text-red-600 text-sm')
			end
		end

		return nil
	end
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class='flex items-start left-0 top-0 bg-pink-600 w-full shadow-md z-40 lg:px-32 '>
  <div class='flex flex-col lg:flex-row'>
    <div class='h-8 w-8 my-3 mx-6 block lg:inline-block'>
      <%= link_to root_path do %>
        <svg class='text-pink-200 fill-current hover:text-white' version="1.1" id="Medium_w_x2F__circle" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             x="0px" y="0px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
          <path d="M10,0.3999634c-5.3019409,0-9.5999756,4.2980957-9.5999756,9.6000366S4.6980591,19.5999756,10,19.5999756
            S19.5999756,15.3019409,19.5999756,10S15.3019409,0.3999634,10,0.3999634z M14.2000122,7.666687h-0.1165771
            c0,0-0.3500977,0-0.3500977,0.3500977c0,0.3500366,0,3.9666748,0,3.9666748s0,0.3497925,0.3500977,0.3497925h0.1165771v0.9333496
            h-2.7999878V12.333252h0.4666138V7.9933472h-0.0466309l-1.4301147,5.2732544H9.1304321L7.7133179,7.9933472H7.666687v4.3399048
            h0.4666748v0.9333496h-2.333374V12.333252h0.1165771c0,0,0.3500977,0,0.3500977-0.3500366s0-3.9667358,0-3.9667358
            s0-0.3497925-0.3500977-0.3497925H5.7999878V6.7333984H8.895874l1.0858765,4.0408325h0.0357666l1.0959473-4.0408325h3.0865479
            V7.666687z"/>
        </svg>
      <% end %>
    </div>
    <div class='hidden lg:flex' data-action="nav">
      <%= link_to("Portfolio", portfolio_items_path, class: "nav-item") %>
      <%= link_to("Blog", posts_path, class: "nav-item") %>
      <% if user_signed_in? %>
      	<%= link_to("New Portfolio Item", new_portfolio_item_path, class: "nav-item") %>
  	    <%= link_to("New Blog Post", new_post_path, class: "nav-item") %>
        <%= link_to("Log Out", destroy_user_session_path, method: :delete, class: "nav-item") %>
      <% else %>        
        <%= link_to("Log In", new_user_session_path, class: "nav-item") %>
      <% end %>
    </div>
  </div>
  <div class='inline-block m-2 py-2 px-4 ml-auto border border-pink-200 rounded z-50 cursor-pointer lg:hidden hover:border-whitez' data-action="toggle-nav">
    <svg xmlns="http://www.w3.org/2000/svg" class="text-pink-200 fill-current hover:text-white" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/></svg>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="overflow-y-auto bg-gray-300 min-h-screen">
      <%= yield %>
    </div>
  </body>
</html>

app/views/portfolio_items/_form.html.erb
<div class='card form-card'>
  <%= form_with(model: portfolio_item, local: true) do |form| %>
    <div class='block mb-4'>
      <%= form.label :youtube_url, class: 'label', text: "YouTube URL" %>
      <%= form.text_field :youtube_url, class: "form-input input w-1/2 #{"input-error" if @portfolio_item.errors.include?(:youtube_url)}", placeholder: "Please include the full URL" %>
      <%= inline_error(:youtube_url, @portfolio_item) %>
    </div>

    <div class='block my-4'>
      <%= form.label :title, class: 'label' %>
      <%= form.text_field :title, class: "form-input input w-1/2 #{"input-error" if @portfolio_item.errors.include?(:title)}" %>
      <%= inline_error(:title, @portfolio_item) %>
    </div>

    <div class='block my-4'>
      <%= form.label :description, class: 'label' %>
      <%= form.text_area :description, class: "form-textarea input w-full #{"input-error" if @portfolio_item.errors.include?(:description)}" %>
      <%= inline_error(:description, @portfolio_item) %>
    </div>

    <div class='block my-4'>
      <%= form.label :preview_image, class: 'label' %>
      <% if @portfolio_item.preview_image.attached? && @portfolio_item.preview_image.variable? %>
        <%= image_tag @portfolio_item.preview_image.variant(resize_to_limit: [300, 300]), class: 'mb-4' %>
      <% end %>
      <%= form.file_field :preview_image, class: "text-gray-900", direct_upload: true %>
    </div>

    <%= form.submit class: 'button shadow-md mt-6' %>
  <% end %>
</div>

app/views/portfolio_items/edit.html.erb
<div class='pt-16 pb-4 w-full max-w-2xl mx-auto text-center'>
	<h1 class='text-xl text-gray-700'>Editing Portfolio Item</h1>
</div>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolio_items/home.html.erb
<div class='flex flex-col lg:flex-row min-h-screen'>
	<div class='bg-gray-100 w-full lg:w-3/5 lg:pr-8 lg:pl-4 flex items-end home-pattern'>
		<%= image_tag 'mady_headshot.png', class: 'hidden w-108 lg:block' %>
		<div class='w-full mx-2 my-8 p-4 self-center card lg:w-124 lg:-ml-24'>
			<div class='relative overflow-hidden pt-responsive'>
				<iframe class='absolute top-0 left-0 w-full h-full' src="https://www.youtube.com/embed/uVI_Rc70K8w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
			</div>
			<div class="flex content-start items-center border-b border-teal-500 lg:block">
				<%= image_tag 'mady_headshot_close.png', class: 'inline-block rounded-full shadow-md m-4 ml-0 pt-1 w-20 h-20 border-4 border-white bg-gray-200 object-contain lg:hidden' %>
				<div class='inline-block flex-shrink mt-6 pb-4 lg:block'>
					<h1 class='text-2xl font-semibold font-headline leading-none text-gray-900 lg:text-3xl'>
						Sports news delivered 
						<br><span class='text-pink-600'>on the money every time.</span>
					</h1>
				</div>
			</div>
			<div class='mt-4'>
				<p class='text-md text-gray-700 leading-snug tracking-wide'>
					When I get in front of the camera to deliver my segment, I make
					sure that it gets delivered correctly and with passion every
					time. Come take a look at my some of my work on this page or
					<%= link_to "in my portfolio", portfolio_items_path, class: 'link' %>.
					You can also read some of my writing <%= link_to "on my blog", posts_path, class: 'link' %>.
				</p>
			</div>
		</div>
	</div>
	<div class='bg-gray-300 w-full px-2 py-6 flex flex-col justify-start lg:w-2/5 lg:px-8 lg:pt-12'>
		<!-- Todo: come backa and style these  -->
		<% unless @portfolio_items.empty? %>
			<div class='my-2 text-center'>
				<h2 class='text-gray-900 leading-tight text-3xl lg:text-4xl'>Portfolio Items</h2>
			</div>
			<% @portfolio_items.each do |portfolio_item| %>
		    <div class='card p-4 my-2 max-w-xl w-full mx-auto shadow-none'>
		      <div class='flex'>
		        <% unless portfolio_item.preview_image.attached? %>
		          <div class='w-32 h-32 mr-8 rounded-lg border border-teal-500 bg-teal-100 self-center flex-shrink-0'>
		            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="fill-current text-teal-500 object-fill"><path class="heroicon-ui" d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm14 12v-2h-2v2h2zm0 2h-2v2h2v-2zM5 15h2v-2H5v2zm0 2v2h2v-2H5zm14-8h-2v2h2V9zm0-2V5h-2v2h2zM5 9v2h2V9H5zm0-2h2V5H5v2zm4 4h6V5H9v6zm0 2v6h6v-6H9z"/></svg>
		          </div>
		        <% else %>
		          <%= image_tag portfolio_item.preview_image, class: 'w-32 h-32 mr-8 rounded-lg border border-teal-500 bg-teal-100 self-center flex-shrink-0 object-cover object-inset', alt: "Preview image for portfolio item" %>
		        <% end %>  
		        <div>
		          <h2 class='text-xl font-semibold text-gray-900 lg:text-2xl '>
		            <%= link_to(portfolio_item.title, portfolio_item, class: 'no-underline link') %>
		          </h2>
		          <p class='text-sm text-gray-700 leading-snug tracking-wide lg:text-base'>
		            <%= truncate(portfolio_item.description, length: 150, omission: '... (continued)') %>
		          </p>
						</div>
					</div>
				</div>
			<% end %>
		<% else %>
			<div class='mt-8 mb-8 text-center'>
				<h2 class='text-gray-900 leading-tight text-4xl'>Portfolio Items</h2>
			</div>
			<div class='card p-4 mb-16 w-full max-w-lg mx-auto text-center lg:shadow-none'>
				<%= image_tag 'empty.svg', class: 'w-64 h-auto mx-auto mt-4 mb-8' %>
				<p class='text-md text-gray-700 tracking-wide'>Looks like there are no porfolio items published yet.</p>
			</div>
		<% end %>
	</div>
</div>

app/views/portfolio_items/index.html.erb
<div class='mt-16 w-full max-w-2xl mx-auto text-center'>
  <h1 class='text-xl text-gray-700'>Portfolio</h1>
</div>

<% unless @portfolio_items.empty? %>
  <% @portfolio_items.each do |portfolio_item| %>
    <div class='card p-4 my-6 shadow-lg max-w-2xl mx-auto'>
      <div class='flex'>
        <% unless portfolio_item.preview_image.attached? %>
          <div class='w-32 h-32 mr-8 rounded-lg border border-teal-500 bg-teal-100 self-center flex-shrink-0'>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="fill-current text-teal-500 object-fill"><path class="heroicon-ui" d="M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zm14 12v-2h-2v2h2zm0 2h-2v2h2v-2zM5 15h2v-2H5v2zm0 2v2h2v-2H5zm14-8h-2v2h2V9zm0-2V5h-2v2h2zM5 9v2h2V9H5zm0-2h2V5H5v2zm4 4h6V5H9v6zm0 2v6h6v-6H9z"/></svg>
          </div>
        <% else %>
          <%= image_tag portfolio_item.preview_image, class: 'w-32 h-32 mr-8 rounded-lg border border-teal-500 bg-teal-100 self-center flex-shrink-0 object-cover object-inset', alt: "Preview image for portfolio item" %>
        <% end %>  
        <div>
          <h2 class='text-2xl font-semibold text-gray-900'>
            <%= link_to(portfolio_item.title, portfolio_item, class: 'no-underline link') %>
          </h2>
          <p class='text-md text-gray-700 leading-snug tracking-wide'>
            <%= truncate(portfolio_item.description, length: 150, omission: '... (continued)') %>
          </p>
          <% if user_signed_in? %>
            <div class='flex mt-4 mb-2'>
              <%= link_to 'Edit', edit_portfolio_item_path(portfolio_item), class: 'button mr-2 shadow-md' %>
              <%= link_to 'Destroy', portfolio_item, class: 'button mx-2 bg-gray-500 hover:bg-gray-600', method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class='card p-4 my-6 shadow-lg max-w-xl mx-auto text-center'>
    <%= image_tag 'empty.svg', class: 'w-64 h-auto mx-auto mt-4 mb-8' %>
    <p class='text-md text-gray-700 tracking-wide'>Looks like there are no portfolio items published yet.</p>
  </div>
<% end %>

app/views/portfolio_items/new.html.erb
<div class='pt-16 pb-4 w-full max-w-2xl mx-auto text-center'>
	<h1 class='text-xl text-gray-700'>New Portfolio Item</h1>
</div>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolio_items/show.html.erb
<div class='w-fill max-w-2xl p-4 mt-16 mb-12 mx-auto card'>
	<div class='relative overflow-hidden pt-responsive'>
		<iframe class='absolute top-0 left-0 w-full h-full' src="https://www.youtube.com/embed/<%= @portfolio_item.youtube_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<div class='mt-6 pb-4 border-b border-teal-500'>
		<%= content_tag :h1, @portfolio_item.title, class: 'text-3xl font-semibold font-headline leading-none text-gray-900' %>
	</div>
	<div class='mt-4'>
		<%= content_tag :p, @portfolio_item.description, class: 'text-md text-gray-700 leading-snug tracking-wide' %>
	</div>

	<div class='mt-8 mb-4'>
		<% if user_signed_in? %>
			<%= link_to 'Edit', edit_portfolio_item_path(@portfolio_item), class: 'button text-lg ml-0 mt-4 py-3 px-8' %>
		<% end %>
	</div>
</div>

app/views/posts/_form.html.erb
<div class='card form-card'>
  <%= form_with(model: post, local: true, class:'form-style') do |form| %>
    <div class='block mb-8'>
      <%= form.label :title, class: 'label' %>
      <%= form.text_field :title, class: "form-input input w-1/2 #{"input-error" if @post.errors.include?(:title)}" %>
      <%= inline_error(:title, @post) %>
    </div>

    <div class='block my-4'>
      <%= form.label :summary, class: 'label' %>
      <%= form.text_area :summary, class: "form-textarea input w-full #{"input-error" if @post.errors.include?(:summary)}" %>
      <%= inline_error(:summary, @post) %>
    </div>

    <div class='block my-8'>
      <%= form.label :content, class: 'label' %>
      <%= form.rich_text_area :content, class: "input #{"input-error" if @post.errors.include?(:content)}" %>
      <%= inline_error(:content, @post) %>
    </div>

    <div class='block my-4'>
      <%= form.label :header_image, class: 'label' %>
      <% if @post.header_image.attached? && @post.header_image.variable? %>
        <%= image_tag @post.header_image.variant(resize_to_limit: [300, 300]), class: 'mb-4' %>
      <% end %>
      <%= form.file_field :header_image, class:'text-gray-900', direct_upload: true %>
    </div>

    <%= form.submit class: 'button shadow-md mt-6' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class='pt-16 pb-4 w-full max-w-2xl mx-auto text-center'>
	<h1 class='text-xl text-gray-700'>Editing Post</h1>
</div>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<div class='mt-16 w-full max-w-2xl mx-auto text-center'>
  <h1 class='text-xl text-gray-700'>Blog</h1>
</div>

<% unless @posts.empty? %>
  <% @posts.each do |post| %>
    <div class='card p-4 my-6 shadow-lg max-w-2xl mx-auto'>
      <div class='flex'>
        <div>
          <h2 class='text-2xl font-semibold text-gray-900'>
            <%= link_to(post.title, post, class: 'no-underline link') %>
          </h2>
          <p class='text-md text-gray-700 leading-snug tracking-wide'>
            <%= post.summary %>
          </p>
          <p class='mt-4 text-md text-gray-400 font-light leading-snug tracking-wide'>
            Published on <%= post.created_at.to_date.to_s(:long_ordinal) %>
          </p>
          <% if user_signed_in? %>
            <div class='flex mt-4 mb-2'>
              <%= link_to 'Edit', edit_post_path(post), class: 'button mr-2 shadow-md' %>
              <%= link_to 'Destroy', post, class: 'button mx-2 bg-gray-500 hover:bg-gray-600', method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class='card p-4 my-6 shadow-lg max-w-xl mx-auto text-center'>
    <%= image_tag 'blog.svg', class: 'w-64 h-auto mx-auto mt-4 mb-8' %>
    <p class='text-md text-gray-700 tracking-wide'>Looks like there are no posts published yet.</p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class='pt-16 pb-4 w-full max-w-2xl mx-auto text-center'>
	<h1 class='text-xl text-gray-700'>New Post</h1>
</div>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class='h-108 w-full bg-teal-300 blog-pattern'>
	<% if @post.header_image.attached? %>
		<%= image_tag @post.header_image, class: 'w-full h-full object-cover object-center relative z-0', alt: "Article header image" %>
	<% end %>
</div>

<div class='w-fill max-w-2xl p-4 -mt-84 mb-12 mx-auto card relative z-10'>
	<div class='mt-6 pb-4 border-b border-pink-500'>
		<%= content_tag :h1, @post.title, class: 'text-4xl font-semibold font-headline leading-none text-gray-900' %>
		<p class='mt-2 text-md text-gray-400 font-light leading-snug tracking-wide'>
	    Published on <%= @post.created_at.to_date.to_s(:long_ordinal) %>
	  </p>
	</div>

	<div class='my-4'>
		<%= content_tag :p, @post.summary, class: 'text-base text-gray-600 leading-tight tracking-wider' %>
	</div>

	<div class='mt-4 mb-4'>
		<% if user_signed_in? %>
			<%= link_to 'Edit', edit_post_path(@post), class: 'button text-md ml-0 mt-4' %>
		<% end %>
	</div>

	<div class='my-12'>
		<%= @post.content %>
	</div>

</div>